### PR TITLE
Fix validator dependencies

### PR DESCRIPTION
**Pull request by J-N-K**
Without these dependencies the `validator` project cannot be build. The build still fails due to a validation error in a test, though.

```
[INFO] --- compiler:2.3.2:compile (default-compile) @ validator ---
[INFO] Compiling 10 source files to /Users/jan/git/mustangproject/validator/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[23,28] error: package org.apache.commons.io does not exist
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[24,16] error: package org.dom4j does not exist
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[25,16] error: package org.dom4j does not exist
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[26,19] error: package org.dom4j.io does not exist
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[27,19] error: package org.dom4j.io does not exist
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[112,14] error: cannot find symbol
[ERROR]  class ZUGFeRDValidator
/Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[285,2] error: cannot find symbol
[ERROR]  class ZUGFeRDValidator
/Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[285,24] error: cannot find symbol
[ERROR]  class ZUGFeRDValidator
/Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[287,11] error: package org.dom4j does not exist
[ERROR] /Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[289,14] error: cannot find symbol
[ERROR]  class ZUGFeRDValidator
/Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[290,11] error: cannot find symbol
[ERROR]  class ZUGFeRDValidator
/Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[293,2] error: cannot find symbol
[ERROR]  class ZUGFeRDValidator
/Users/jan/git/mustangproject/validator/src/main/java/org/mustangproject/validator/ZUGFeRDValidator.java:[293,25] error: cannot find symbol
[INFO] 13 errors 
```

### CODE REVIEW

**Comment by J-N-K** [comment]
The remaining test failure is fixed by #471.
