### ISSUE TITLE
fontbox - NoSuchMethodError - TTFSubsetter.forceInvisible()

### ISSUE THREAD

**Issue by ial-igg** [ZUGFeRD/mustangproject#1040]
Hi,

working with library-2.20.0-shaded.jar there is a call from pdfbox(must be 3.0.6)

I have an error message:
java.lang.NoSuchMethodError: org/apache/fontbox/ttf/TTFSubsetter.forceInvisible(I)V

Exactly:
-------------------
Exception in thread "AgentThread: JavaAgent" java.lang.NoSuchMethodError: org/apache/fontbox/ttf/TTFSubsetter.forceInvisible(I)V (loaded from <Unknown> by lotus.domino.AgentLoader@d035b558) called from class org.apache.pdfbox.pdmodel.font.TrueTypeEmbedder (loaded from <Unknown> by lotus.domino.AgentLoader@d035b558).
	at org.apache.pdfbox.pdmodel.font.TrueTypeEmbedder.subset(TrueTypeEmbedder.java:324)
	at org.apache.pdfbox.pdmodel.font.PDType0Font.subset(PDType0Font.java:304)
	at org.apache.pdfbox.pdmodel.PDDocument.subsetDesignatedFonts(PDDocument.java:1064)
	at org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1052)
-------------------

In pom.properties of fontbox stands "version=3.0.3".

Could it be a version conflict or something else?

How to fix this?

**Comment by langfr** [comment]
You're right, org.apache.pdfbox:fontbox:jar is of version 3.0.3, a dependency of org.apache.xmlgraphics:fop-core:jar:2.11.
And lib org.apache.pdfbox:pdfbox:jar is of version 3.0.6.

Added an exclusion of org.apache.pdfbox:fontbox to org.apache.xmlgraphics:fop-core, then org.apache.pdfbox:fontbox 3.0.6 as dependency of org.apache.pdfbox:pdfbox:jar 3.0.6 is used for shaded jar.

PR #1044 created.

Dependency tree before:
```
[INFO] --- dependency:3.6.1:tree (default-cli) @ library ---
[INFO] org.mustangproject:library:jar:2.22.1-SNAPSHOT
[INFO] +- org.slf4j:slf4j-api:jar:2.0.17:compile
[INFO] +- net.sf.saxon:Saxon-HE:jar:12.8:compile
[INFO] |  +- org.xmlresolver:xmlresolver:jar:5.3.3:compile
[INFO] |  \- org.xmlresolver:xmlresolver:jar:data:5.3.3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.17.3:compile
**[INFO] +- org.apache.xmlgraphics:fop-core:jar:2.11:compile**
[INFO] |  +- org.apache.xmlgraphics:batik-anim:jar:1.19:compile
[INFO] |  |  +- org.apache.xmlgraphics:batik-css:jar:1.19:compile
[INFO] |  |  +- org.apache.xmlgraphics:batik-dom:jar:1.19:compile
[INFO] |  |  +- org.apache.xmlgraphics:batik-ext:jar:1.19:compile
[INFO] |  |  +- org.apache.xmlgraphics:batik-parser:jar:1.19:compile
[INFO] |  |  +- org.apache.xmlgraphics:batik-shared-resources:jar:1.19:compile
[INFO] |  |  +- org.apache.xmlgraphics:batik-svg-dom:jar:1.19:compile
[INFO] |  |  +- org.apache.xmlgraphics:batik-util:jar:1.19:compile
[INFO] |  |  |  +- org.apache.xmlgraphics:batik-constants:jar:1.19:compile
[INFO] |  |  |  \- org.apache.xmlgraphics:batik-i18n:jar:1.19:compile
[INFO] |  |  \- xml-apis:xml-apis-ext:jar:1.3.04:compile
[INFO] |  +- org.apache.xmlgraphics:batik-awt-util:jar:1.19:compile
[INFO] |  +- org.apache.xmlgraphics:batik-bridge:jar:1.19:compile
[INFO] |  |  +- org.apache.xmlgraphics:batik-script:jar:1.19:compile
[INFO] |  |  \- org.apache.xmlgraphics:batik-xml:jar:1.19:compile
[INFO] |  +- org.apache.xmlgraphics:batik-extension:jar:1.19:compile
[INFO] |  +- org.apache.xmlgraphics:batik-gvt:jar:1.19:compile
[INFO] |  +- org.apache.xmlgraphics:batik-transcoder:jar:1.19:compile
[INFO] |  |  \- org.apache.xmlgraphics:batik-svggen:jar:1.19:compile
[INFO] |  +- org.apache.xmlgraphics:batik-codec:jar:1.19:compile
[INFO] |  +- org.apache.xmlgraphics:fop-events:jar:2.11:compile
[INFO] |  |  \- com.thoughtworks.qdox:qdox:jar:1.12:compile
[INFO] |  +- org.apache.xmlgraphics:fop-util:jar:2.11:compile
[INFO] |  +- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.11:compile
[INFO] |  +- commons-io:commons-io:jar:2.17.0:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.3.0:compile
**[INFO] |  \- org.apache.pdfbox:fontbox:jar:3.0.3:compile**
[INFO] +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.2:compile
[INFO] |  \- jakarta.activation:jakarta.activation-api:jar:2.1.3:compile
[INFO] +- org.apache.pdfbox:preflight:jar:3.0.6:compile
[INFO] |  \- org.apache.pdfbox:xmpbox:jar:3.0.6:compile
**[INFO] +- org.apache.pdfbox:pdfbox:jar:3.0.6:compile**
[INFO] |  \- org.apache.pdfbox:pdfbox-io:jar:3.0.6:compile
[INFO] +- org.dom4j:dom4j:jar:2.1.5:compile
[INFO] +- com.helger:en16931-cii2ubl:jar:2.3.1:compile
[INFO] |  +- com.helger.commons:ph-commons:jar:11.2.6:compile
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- com.helger.commons:ph-jaxb:jar:11.2.6:compile
[INFO] |  +- com.helger.commons:ph-xml:jar:11.2.6:compile
[INFO] |  +- com.helger.commons:ph-datetime:jar:11.2.6:compile
[INFO] |  +- com.helger.cii:ph-cii-d16b:jar:3.1.0:compile
[INFO] |  |  \- com.helger.commons:ph-jaxb-adapter:jar:11.1.11:compile
[INFO] |  +- com.helger.ubl:ph-ubl21:jar:9.0.3:compile
[INFO] |  |  +- com.helger.xsd:ph-xsds-xmldsig:jar:3.0.0:compile
[INFO] |  |  +- com.helger.xsd:ph-xsds-xades132:jar:3.0.0:compile
[INFO] |  |  +- com.helger.xsd:ph-xsds-xades141:jar:3.0.0:compile
[INFO] |  |  \- com.helger.xsd:ph-xsds-ccts-cct-schemamodule:jar:3.0.0:compile
[INFO] |  +- com.helger.ubl:ph-ubl22:jar:9.0.3:compile
[INFO] |  |  \- com.helger.xsd:ph-xsds-xmldsig11:jar:3.0.0:compile
[INFO] |  +- com.helger.ubl:ph-ubl23:jar:9.0.3:compile
[INFO] |  \- com.helger.ubl:ph-ubl24:jar:9.0.3:compile
[INFO] +- org.skyscreamer:jsonassert:jar:2.0-rc1:test
[INFO] |  \- org.json:json:jar:20240303:test
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.13.4:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.13.4:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.junit.vintage:junit-vintage-engine:jar:5.13.4:test
[INFO] |  +- org.junit.platform:junit-platform-engine:jar:1.13.4:test
[INFO] |  \- junit:junit:jar:4.13.2:test
[INFO] |     \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.xmlunit:xmlunit-core:jar:2.10.3:test
[INFO] +- org.xmlunit:xmlunit-assertj:jar:2.10.3:test
[INFO] |  +- org.assertj:assertj-core:jar:2.9.0:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.12.23:test
[INFO] \- org.glassfish.jaxb:jaxb-runtime:jar:4.0.5:test
[INFO]    \- org.glassfish.jaxb:jaxb-core:jar:4.0.5:test
[INFO]       +- org.eclipse.angus:angus-activation:jar:2.0.2:test
[INFO]       +- org.glassfish.jaxb:txw2:jar:4.0.5:test
[INFO]       \- com.sun.istack:istack-commons-runtime:jar:4.1.2:test
```

**Comment by ial-igg** [comment]
Thank you!
I would like to wait for the new official version.
I hope it will be available soon.
Have a good weekend!

**Comment by jstaerk** [comment]
Thanks a lot @langfr , pr was accepted, will be part of the next version

**Comment by ial-igg** [comment]
Thank you so much!
